allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@eloqnt/config@0.1.0'
  - '@eloqnt/format-json@0.1.0'
  - '@eloqnt/format-po@0.1.0'
  - icu-minify@4.14.2
  - next-intl-swc-plugin-extractor@4.14.2
  - next-intl@4.14.2
  - use-intl@4.14.2
